<?php
namespace PackageInfo;

use PackageInfo\Exception\PackageNotInstalledException;

/**
 * This class is generated by thadafinser/package-info
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Package
{
    const PACKAGES = [];

    /**
     * 
     * @var string
     */
    private $name;
    
    /**
     * 
     * @param string $name
     * @throws PackageNotInstalledException
     */
    public function __construct($name)
    {
        $this->name = $name;
        
        if (! $this->isInstalled($name)) {
            throw new PackageNotInstalledException('Package "'.$name.'" is not installed through composer, or you installed it with the flag --no-scripts');
        }
    }
    
    /**
     * Check if the given package is installed
     * 
     * @return boolean
     */
    public static function isInstalled($name)
    {
        if (array_key_exists($name, self::PACKAGES)) {
            return true;
        }
        
        return false;
    }
    
    /**
     * NOTE: i removed per default all other methods.
     * They are not static and on Package::__construct() the exception will be thrown
     */
}
